services:
  backend:
    image: node:20-alpine
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - 3001:3001
    container_name: backend
    command: sh -c 'npm i && npm run start'
  frontend:
    image: node:20-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - 3000:3000
    container_name: frontend
    command: sh -c 'npm i && npm run start'
